export const MENU: any = [
  {
    id: 300,
    idParent: '',
    display: 'User Management',
    name: 'admin-user',
    path: '/admin/users',
    icon: 'fal fa-user',
    hidden: false,
    search: true,
    privileges: ['view', 'create', 'update', 'delete', 'reset-password'],
    divider: false,
    no: 300,
  },
  {
    id: 301,
    idParent: '',
    display: 'Role Manajemen',
    name: 'role',
    path: '/admin/role',
    icon: 'far fa-key',
    hidden: false,
    search: true,
    privileges: ['view', 'create', 'update', 'delete', 'setting'],
    divider: false,
    no: 301,
  },
  {
    id: 302,
    idParent: '',
    display: 'Menu Manajemen',
    name: 'menu',
    path: '/admin/menu',
    icon: 'far fa-bars',
    hidden: false,
    search: true,
    privileges: ['view', 'create', 'update', 'delete', 'sort'],
    divider: false,
    no: 302,
  },
  {
    id: 303,
    idParent: '',
    display: 'Pengaturan Aplikasi',
    name: 'settings',
    path: '/admin/settings',
    icon: 'far fa-cog',
    hidden: false,
    search: false,
    privileges: ['view', 'create', 'update', 'delete'],
    divider: false,
    no: 302,
  },
  {
    id: 303,
    idParent: '',
    display: 'Pengaturan Profil',
    name: 'profile',
    path: '/account/profile',
    icon: 'far fa-user',
    hidden: false,
    search: false,
    privileges: ['view', 'update'],
    divider: false,
    no: 302,
  }
];
